repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-toml
    - id: mixed-line-ending
    - id: check-json
    - id: pretty-format-json
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
    - id: typos
      args: []
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    - id: fmt
    - id: cargo-check
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.0.0
    hooks:
    - id: oxipng
  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.6
    hooks:
    -   id: jshint
  - repo: local
    hooks:
      - id: cargo-test
        name: Run tests
        entry: cargo test
        language: system
