[package]
name = "surfer-translation-types"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre.workspace = true
derive_more.workspace = true
ecolor.workspace = true
num.workspace = true
pyo3.workspace = true
serde.workspace = true
