class ValueKind:
    @classmethod
    def Normal(cls): ...

    @classmethod
    def Undef(cls): ...

    @classmethod
    def HighImp(cls): ...

    @classmethod
    def Custom(cls, color: tuple[int, int, int, int]): ...

    @classmethod
    def Warn(cls): ...

    @classmethod
    def DontCare(cls): ...

    @classmethod
    def Weak(cls): ...
