mod benchmark;
mod command_prompt;
mod commands;
mod signal_canvas;
mod translation;
mod view;
mod viewport;

use camino::Utf8PathBuf;
use clap::Parser;
use color_eyre::eyre::anyhow;
use color_eyre::eyre::Context;
use color_eyre::Result;
use eframe::egui;
use eframe::epaint::Vec2;
use fastwave_backend::parse_vcd;
use fastwave_backend::ScopeIdx;
use fastwave_backend::SignalIdx;
use fastwave_backend::VCD;
use fern::colors::ColoredLevelConfig;
use log::error;
use log::info;
use num::bigint::ToBigInt;
use num::BigInt;
use num::BigRational;
use num::FromPrimitive;
use num::ToPrimitive;
use progress_streams::ProgressReader;
use pyo3::append_to_inittab;

use translation::pytranslator::surfer;
use translation::pytranslator::PyTranslator;
use translation::spade::SpadeTranslator;
use translation::SignalInfo;
use translation::Translator;
use translation::TranslatorList;
use view::TraceIdx;
use viewport::Viewport;

use std::collections::HashMap;
use std::collections::HashSet;
use std::fs::File;
use std::sync::atomic::AtomicU64;
use std::sync::atomic::Ordering;
use std::sync::mpsc::channel;
use std::sync::mpsc::Receiver;
use std::sync::Arc;

#[derive(clap::Parser)]
struct Args {
    vcd_file: Utf8PathBuf,
    #[clap(long)]
    spade_state: Option<Utf8PathBuf>,
    #[clap(long)]
    spade_top: Option<String>,
}

type VarListIdx = u32;

fn main() -> Result<()> {
    color_eyre::install()?;

    let colors = ColoredLevelConfig::new()
        .error(fern::colors::Color::Red)
        .warn(fern::colors::Color::Yellow)
        .info(fern::colors::Color::Green)
        .debug(fern::colors::Color::Blue)
        .trace(fern::colors::Color::White);

    let stdout_config = fern::Dispatch::new()
        .level(log::LevelFilter::Info)
        .format(move |out, message, record| {
            out.finish(format_args!(
                "[{}] {}",
                colors.color(record.level()),
                message
            ))
        })
        .chain(std::io::stdout());

    fern::Dispatch::new().chain(stdout_config).apply()?;

    // Load python modules we deinfe in this crate
    append_to_inittab!(surfer);

    let args = Args::parse();
    let vcd_file = args.vcd_file.clone();

    let state = State::new(args)?;

    let options = eframe::NativeOptions {
        initial_window_size: Some(egui::vec2(1920., 1080.)),
        ..Default::default()
    };
    eframe::run_native(
        &format!("Surfer: {}", &vcd_file),
        options,
        Box::new(|_cc| Box::new(state)),
    );

    Ok(())
}

pub struct VcdData {
    inner: VCD,
    active_scope: Option<ScopeIdx>,
    /// Root signals to display
    next_varlist_idx: VarListIdx,
    signals: Vec<(u32, SignalIdx, SignalInfo)>,
    /// These hashmaps contain a list of all full (i.e., top.dut.mod1.signal) signal or scope
    /// names to their indices. They have to be initialized using the initialize_signal_scope_maps
    /// function after this struct is created.
    signals_to_ids: HashMap<String, SignalIdx>,
    scopes_to_ids: HashMap<String, ScopeIdx>,
    viewport: Viewport,
    num_timestamps: BigInt,
    /// Name of the translator used to translate this trace
    signal_format: HashMap<TraceIdx, String>,
    cursor: Option<BigInt>,
}

pub enum SignalDescriptor {
    Id(SignalIdx),
    Name(String),
}

pub enum ScopeDescriptor {
    Id(ScopeIdx),
    Name(String),
}

pub enum Message {
    HierarchyClick(ScopeIdx),
    AddSignal(SignalDescriptor),
    AddScope(ScopeDescriptor),
    RemoveSignal(VarListIdx),
    SignalFormatChange(TraceIdx, String),
    // Reset the translator for this signal back to default. Sub-signals,
    // i.e. those with the signal idx and a shared path are also reset
    ResetSignalFormat(TraceIdx),
    CanvasScroll {
        delta: Vec2,
    },
    CanvasZoom {
        mouse_ptr_timestamp: BigRational,
        delta: f32,
    },
    CursorSet(BigInt),
    VcdLoaded(Box<VCD>),
    Error(color_eyre::eyre::Error),
    TranslatorLoaded(Box<dyn Translator + Send>),
    /// Take note that the specified translator errored on a `translates` call on the
    /// specified signal
    BlacklistTranslator(SignalIdx, String),
    ToggleSidePanel,
    ShowCommandPrompt(bool),
}

pub struct State {
    vcd: Option<VcdData>,
    /// The offset of the left side of the wave window in signal timestamps.
    control_key: bool,
    /// Which translator to use for each signal
    translators: TranslatorList,

    /// Receiver for messages generated by other threads
    msg_receiver: Receiver<Message>,

    /// The number of bytes loaded from the vcd file
    vcd_progess: (Option<u64>, Arc<AtomicU64>),

    // Vector of translators which have failed at the `translates` function for a signal.
    blacklisted_translators: HashSet<(SignalIdx, String)>,
    /// buffer for the command input
    command_prompt: command_prompt::CommandPrompt,
    /// Flag to show/hide the side panel
    show_side_panel: bool,
}

impl State {
    fn new(args: Args) -> Result<State> {
        let vcd_filename = args.vcd_file;

        let (sender, receiver) = channel();

        // Basic translators that we can load quickly
        let translators = TranslatorList::new(
            vec![
                Box::new(translation::HexTranslator {}),
                Box::new(translation::UnsignedTranslator {}),
                Box::new(translation::ExtendingBinaryTranslator {}),
            ],
            vec![],
        );

        // Long running translators which we load in a thread
        {
            let sender = sender.clone();
            std::thread::spawn(move || {
                if let (Some(top), Some(state)) = (args.spade_top, args.spade_state) {
                    let t = SpadeTranslator::new(&top, &state);
                    match t {
                        Ok(result) => sender.send(Message::TranslatorLoaded(Box::new(result))),
                        Err(e) => sender.send(Message::Error(e)),
                    }?;
                } else {
                    info!("spade-top and spade-state not set, not loading spade translator");
                }

                let pytranslator = PyTranslator::new(
                    "SurferTranslator",
                    "translation_test.py",
                    vec![(
                        "type_file".to_string(),
                        "/home/frans/Documents/fpga/spadev/build/spade_types.ron".to_string(),
                    )]
                    .into_iter()
                    .collect(),
                );
                match pytranslator {
                    Ok(result) => sender.send(Message::TranslatorLoaded(Box::new(result))),
                    Err(e) => sender.send(Message::Error(e)),
                }
            });
        }

        // We'll open the file to check if it exists here to panic the main thread if not.
        // Then we pass the file into the thread for parsing
        let file =
            File::open(&vcd_filename).with_context(|| format!("Failed to open {vcd_filename}"))?;

        let total_bytes = file
            .metadata()
            .map(|m| m.len())
            .map_err(|e| info!("Failed to get vcd file metadata {e}"))
            .ok();

        // Progress tracking in bytes
        let progress_bytes = Arc::new(AtomicU64::new(0));
        let reader = {
            let progress_bytes = progress_bytes.clone();
            ProgressReader::new(file, move |progress: usize| {
                progress_bytes.fetch_add(progress as u64, Ordering::SeqCst);
            })
        };

        std::thread::spawn(move || {
            info!("Loading VCD");
            let result = parse_vcd(reader)
                .map_err(|e| anyhow!("{e}"))
                .with_context(|| format!("Failed to parse parse {vcd_filename}"));

            match result {
                Ok(vcd) => sender.send(Message::VcdLoaded(Box::new(vcd))),
                Err(e) => sender.send(Message::Error(e)),
            }
        });

        Ok(State {
            vcd: None,
            control_key: false,
            translators,
            msg_receiver: receiver,
            vcd_progess: (total_bytes, progress_bytes),
            blacklisted_translators: HashSet::new(),
            command_prompt: command_prompt::CommandPrompt {
                visible: false,
                input: String::from(""),
                expanded: String::from(""),
                suggestions: vec![],
            },
            show_side_panel: true,
        })
    }

    // TODO: Rename to process_msg or something
    fn update(&mut self, message: Message) {
        match message {
            Message::HierarchyClick(scope) => {
                let mut vcd = self.vcd.as_mut().expect("HierarchyClick without vcd set");

                vcd.active_scope = Some(scope)
            }
            Message::AddSignal(descriptor) => {
                let vcd = self.vcd.as_mut().expect("AddSignal without vcd set");
                match descriptor {
                    SignalDescriptor::Id(id) => vcd.add_signal(&self.translators, id),
                    SignalDescriptor::Name(name) => {
                        if let Some(id) = vcd.signals_to_ids.get(&name) {
                            vcd.add_signal(&self.translators, *id);
                        } else {
                            error!("Can not add signal \"{name}\" to viewer.");
                        }
                    }
                }
            }
            Message::AddScope(descriptor) => {
                let vcd = self.vcd.as_mut().expect("AddSignal without vcd set");

                let id_option = match descriptor {
                    ScopeDescriptor::Id(id) => Some(id),
                    ScopeDescriptor::Name(name) => vcd.scopes_to_ids.get(&name).copied(),
                };
                if let Some(s) = id_option {
                    let signals = vcd.inner.get_children_signal_idxs(s);
                    for sidx in signals {
                        if !vcd.signal_name(sidx).starts_with("_") {
                            vcd.add_signal(&self.translators, sidx);
                        }
                    }
                }
            }
            Message::RemoveSignal(vidx) => {
                let vcd = self.vcd.as_mut().expect("AddSignal without vcd set");
                vcd.signals.retain(|idx| idx.0 != vidx);
            }
            Message::CanvasScroll { delta } => self.handle_canvas_scroll(delta),
            Message::CanvasZoom {
                delta,
                mouse_ptr_timestamp,
            } => {
                self.vcd
                    .as_mut()
                    .map(|vcd| vcd.handle_canvas_zoom(mouse_ptr_timestamp, delta as f64));
            }
            Message::SignalFormatChange(ref idx @ (ref signal_idx, ref path), format) => {
                let vcd = self
                    .vcd
                    .as_mut()
                    .expect("Signal format change without vcd set");

                if self.translators.all_translator_names().contains(&&format) {
                    *vcd.signal_format.entry(idx.clone()).or_default() = format;

                    if path.is_empty() {
                        let signal = vcd.inner.signal_from_signal_idx(idx.0);
                        let translator = vcd.signal_translator(idx.clone(), &self.translators);
                        let new_info = translator
                            .signal_info(&signal, &vcd.signal_name(idx.0))
                            .unwrap();

                        for (_vidx, i, info) in &mut vcd.signals {
                            if i == signal_idx {
                                *info = new_info;
                                break;
                            }
                        }
                    }
                } else {
                    println!("WARN: No translator {format}")
                }
            }
            Message::ResetSignalFormat(idx) => {
                let vcd = self
                    .vcd
                    .as_mut()
                    .expect("Signal format reset without vcd set");

                vcd.signal_format.remove(&idx);
            }
            Message::CursorSet(new) => {
                self.vcd.as_mut().map(|vcd| vcd.cursor = Some(new));
            }
            Message::VcdLoaded(new_vcd_data) => {
                info!("VCD file loaded");
                let num_timestamps = new_vcd_data
                    .max_timestamp()
                    .as_ref()
                    .map(|t| t.to_bigint().unwrap())
                    .unwrap_or(BigInt::from_u32(1).unwrap());

                let mut new_vcd = VcdData {
                    inner: *new_vcd_data,
                    active_scope: None,
                    next_varlist_idx: 0,
                    signals: vec![],
                    signals_to_ids: HashMap::new(),
                    scopes_to_ids: HashMap::new(),
                    viewport: Viewport::new(0., num_timestamps.clone().to_f64().unwrap()),
                    signal_format: HashMap::new(),
                    num_timestamps,
                    cursor: None,
                };
                new_vcd.initialize_signal_scope_maps();

                self.vcd = Some(new_vcd);
                info!("Done setting up vcd file");
            }
            Message::BlacklistTranslator(idx, translator) => {
                self.blacklisted_translators.insert((idx, translator));
            }
            Message::Error(e) => {
                error!("{e:?}")
            }
            Message::TranslatorLoaded(t) => {
                info!("Translator {} loaded", t.name());
                self.translators.add(t)
            }
            Message::ToggleSidePanel => {
                self.show_side_panel = !self.show_side_panel;
            }
            Message::ShowCommandPrompt(new_visibility) => {
                if !self.command_prompt.visible && new_visibility {
                    self.command_prompt.input = "".to_string();
                    self.command_prompt.suggestions = vec![];
                    self.command_prompt.expanded = "".to_string();
                }
                self.command_prompt.visible = new_visibility;
            }
        }
    }

    pub fn handle_canvas_scroll(
        &mut self,
        // Canvas relative
        delta: Vec2,
    ) {
        if let Some(vcd) = &mut self.vcd {
            // Scroll 5% of the viewport per scroll event.
            // One scroll event yields 50
            let scroll_step = (&vcd.viewport.curr_right - &vcd.viewport.curr_left) / (50. * 20.);

            let target_left = &vcd.viewport.curr_left + scroll_step * delta.y as f64;
            let target_right = &vcd.viewport.curr_right + scroll_step * delta.y as f64;

            vcd.viewport.curr_left = target_left;
            vcd.viewport.curr_right = target_right;
        }
    }
}

impl VcdData {
    pub fn signal_name(&self, idx: SignalIdx) -> String {
        self.inner.signal_from_signal_idx(idx).name()
    }

    pub fn signal_translator<'a>(
        &'a self,
        sig: TraceIdx,
        translators: &'a TranslatorList,
    ) -> &'a dyn Translator {
        let translator_name = self
            .signal_format
            .get(&sig)
            .unwrap_or_else(|| &translators.default);
        let translator = translators.get_translator(translator_name);
        translator
    }

    pub fn handle_canvas_zoom(
        &mut self,
        // Canvas relative
        mouse_ptr_timestamp: BigRational,
        delta: f64,
    ) {
        // Zoom or scroll
        let Viewport {
            curr_left: left,
            curr_right: right,
            ..
        } = &self.viewport;

        let target_left = (left - mouse_ptr_timestamp.to_f64().unwrap()) / delta
            + &mouse_ptr_timestamp.to_f64().unwrap();
        let target_right = (right - mouse_ptr_timestamp.to_f64().unwrap()) / delta
            + &mouse_ptr_timestamp.to_f64().unwrap();

        // TODO: Do not just round here, this will not work
        // for small zoom levels
        self.viewport.curr_left = target_left;
        self.viewport.curr_right = target_right;
    }

    pub fn get_next_varlist_idx(&mut self) -> u32 {
        let next_varlist_idx = self.next_varlist_idx;
        self.next_varlist_idx += 1;
        next_varlist_idx
    }

    // Initializes the scopes_to_ids and signals_to_ids
    // fields by iterating down the scope hierarchy and collectiong
    // the absolute names of all signals and scopes
    pub fn initialize_signal_scope_maps(&mut self) {
        // in scope S and path P, adds all signals x to all_signal_names
        // as [S.]P.x
        // does the same for scopes
        // goes down into subscopes and does the same there
        fn add_scope_signals(scope: ScopeIdx, path: String, vcd: &mut VcdData) {
            let scope_name = vcd.inner.scope_name_by_idx(scope);
            let full_scope_name = if !path.is_empty() {
                format!("{path}.{}", scope_name)
            } else {
                scope_name.to_string()
            };
            vcd.scopes_to_ids.insert(full_scope_name.clone(), scope);

            let signal_idxs = vcd.inner.get_children_signal_idxs(scope);
            for signal in signal_idxs {
                let signal_name = vcd.inner.signal_from_signal_idx(signal).name();
                // TODO: it would be best if this is a setting
                if !signal_name.starts_with('_') {
                    vcd.signals_to_ids
                        .insert(format!("{}.{}", full_scope_name, signal_name), signal);
                }
            }

            for sub_scope in vcd.inner.child_scopes_by_idx(scope) {
                add_scope_signals(sub_scope, full_scope_name.clone(), vcd);
            }
        }

        for root_scope in self.inner.root_scopes_by_idx() {
            add_scope_signals(root_scope, String::from(""), self);
        }
    }

    pub fn add_signal(&mut self, translators: &TranslatorList, sidx: SignalIdx) {
        let signal = self.inner.signal_from_signal_idx(sidx);
        let translator = self.signal_translator((sidx, vec![]), translators);
        let info = translator
            .signal_info(&signal, &self.signal_name(sidx))
            .unwrap();
        let vidx = self.get_next_varlist_idx();
        self.signals.push((vidx, sidx, info))
    }
}
